# -*- coding: utf-8 -*-
"""Lab4_Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EGBIxWPJamssMo9uxAKwL8zPVwo74X6E
"""

import string

d = dict()
iof = open("book.txt")
for line in iof:
  for word in line.split():
    word = word.strip(string.punctuation + string.whitespace)
    word = word.lower()
    if word in d:
      d[word] = d[word] +1
    else:
      d[word] = 1

print(d)
sum = 0
num_diff_words = len(d)
for i, j in d.items():
  sum = sum + j
print("Total number of words in the file is : ", sum)
print("There are ", num_diff_words, " different words in the file")
lst = []
for i , j in d.items():
  lst.append((j , i))
lst.sort(reverse=True)
print("Bellow you can find a sorted list of the iteration of each word in the book")
print(lst)